version: '3'

services:
  web:
    container_name: ApiRestMongo
    restart: always
    build: .
    ports: 
      - 5000:3000
    links:
      - mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  mongo:
    container_name: MongoDbUsers
    image: mongo:latest
    ports:
     - "27017:27017"
    logging:
      driver: none


